### ISSUE TITLE
🚀 Feature  十个Issue，9个都有截图，非常需要支持issue反馈的图片（包括评论）

### ISSUE THREAD

**Issue by Leizhenpeng** [ConnectAI-E/GitMaya#101]

**Comment by lloydzhou** [comment]
![](img_v3_027b_2c6242c3-8e3d-4816-ac53-2473e724434g)  
链接有问题，issues

**Comment by lloydzhou** [comment]
这里主要是需要处理好图床的问题。

**Comment by lloydzhou** [comment]
1. github的issue和pr有自己的图床。从github到飞书是相对比较简单的。只要拿这个url的图片上传飞书，换取一个image_key就可以使用了（这里可能需要一个缓存：相同的url一定时间之类只传一次，换一个相同的image_key就行了）。
2. 但是飞书那边到github就有问题。飞书那边的图现在不能上传到github这边。。。

**Comment by freeziyou** [comment]
从 GitHub 发图，飞书已能够正常显示

**Comment by freeziyou** [comment]
#151
