### ISSUE TITLE
在GIthub那边编辑了issue描述内容之后，飞书这边没有更新!

### ISSUE THREAD

**Issue by Leizhenpeng** [ConnectAI-E/GitMaya#105]
feishu这边有更新吗?

**Comment by Leizhenpeng** [comment]
我现在更新了

**Comment by freeziyou** [comment]
ok

**Comment by Leizhenpeng** [comment]
![](img_v3_027b_92c86104-5608-45f9-976b-1554d1df1d9g)

**Comment by Leizhenpeng** [comment]
应该是图片md的问题，关联 https://github.com/ConnectAI-E/GitMaya/issues/101

**Comment by freeziyou** [comment]
定位到是markdown解析问题，WIP

**Comment by lloydzhou** [comment]
![](img_v3_027b_2cc9919e-7517-4da0-a4d1-ac50bea46fag)  
![](img_v3_027b_96f91985-170f-46c8-a606-cc60df175a8g)  
  
这个应该是群里，另一个人创建issue的时候的时候说是没有同步issue。  
实际上是组成的卡片消息出现了错误，导致这个卡片没有发出去。

**Comment by freeziyou** [comment]
#151 已解决
