### ISSUE TITLE
🚀 Feature 在issue和pr的评论下@人，在飞书也要@对应的人

### ISSUE THREAD

**Issue by Leizhenpeng** [ConnectAI-E/GitMaya#106]
## What's Your Suggestion? 🤔

<img width="375" alt="image" src="https://github.com/ConnectAI-E/GitMaya/assets/50035229/8727b91e-bfe1-404f-97b4-92d59652275e">

现在只是纯文本，应该变成真正的@

同理在飞书上@，GIthub也需要正确的显示
![image](https://github.com/ConnectAI-E/GitMaya/assets/50035229/60eb7071-2451-4994-a005-13171b94c44e)

<img width="667" alt="image" src="https://github.com/ConnectAI-E/GitMaya/assets/50035229/e73d4463-e6c4-44fe-8077-bfb9dedee6ce">

**Comment by freeziyou** [comment]
WIP

**Comment by freeziyou** [comment]
#164
