### ISSUE TITLE
🐞 Bug GIthub上创建Issue，飞书上偶尔会没有提醒

### ISSUE THREAD

**Issue by Leizhenpeng** [ConnectAI-E/GitMaya#107]
## Issue Description 🤔

比如这个issue  https://github.com/ConnectAI-E/GitMaya/issues/98

**Comment by freeziyou** [comment]
可能是网络抖动，目前日志没有看到报错，后续有相同问题再定位日志

**Comment by freeziyou** [comment]
#143 这个issue也没有提示，task id 33271143-9106-4499-be88-2c478f575a01

**Comment by freeziyou** [comment]
#151 已解决
