### ISSUE TITLE
商业项目经常GIthub的代码有多个repo，但在飞书这边是统一的project，希望飞书同一个chat可以关联多个GIthub的repo

### ISSUE THREAD

**Issue by Leizhenpeng** [ConnectAI-E/GitMaya#111]
这个issue关联细节较多这里指出一下

- manager状态下，如果指定了群名，且这个群之前右gitmaya创建的，会匹配此逻辑。如果老群不是，文案指出需要先拉入机器人。

- chat状态下，老群如果是gitmaya创建的，可以在群内关联更多仓库 
- chat状态下，老群如果没有机器人加入，需要先提醒必须拉入机器人，再完成操作
- chat状态下，关联的指令同manage状态下一致
`/match https://github.com/ConnectAI-E/kimi-commits-intellij 群名`

- 由于一个群中有多个仓库，
    - 需要在发送的issue和pr卡片的note部分指明来自的仓库
    - chat模式下，用户需要显示指出在哪个仓库创建issue 指令为
    `repo名 /issue issuexxxxxxxxx @xxx #1abel`
 
 - 在repo、issue、pr的消息卡片下，也支持创建issue
    - 由于都可以确定知道是哪个仓库，均支持/issue 不指定仓库，直接创建issue

**Comment by lloydzhou** [comment]
这里需要考虑清楚一些。不能简单的关联多个repo到一个群。

如果这样做了，chat的命令几乎都不能正确找到操作的repo...

**Comment by lloydzhou** [comment]
把chat的功能弱化就好了，本来view ＋insight的命令在repo的卡片里面就有。
然后issue命令也在repo卡片支持就好了。
这样就算多repo关联一个群，也可以做到功能完备。

**Comment by Leizhenpeng** [comment]
后面给一份详细一点的功能设计~

**Comment by lloydzhou** [comment]
还有一个方案：飞书快捷应用提issue

**Comment by lloydzhou** [comment]
扩展/issue 命令，支持repo参数

**Comment by lloydzhou** [comment]
# 实现：

1. 创建新的chat_group表
2. repo表新增外键
3. 新增迁移脚本，将旧chat_group表数据迁移过来
4. 更新现在系统中与chat_group相关的查询逻辑

**Comment by lloydzhou** [comment]
已经修复并部署到线上环境
