### ISSUE TITLE
repo界面需要优化  

### ISSUE THREAD

**Issue by Leizhenpeng** [ConnectAI-E/GitMaya#113]
1. 增加一下分页，现在ConnectAI全部150多个仓库放在一起，太长了 
 2. 默认优先展示已经关联chat的仓库

**Comment by Dogtiti** [comment]
@lloydzhou @jingfelix 
分页已经加上需要把已经关联的往前面放

**Comment by Leizhenpeng** [comment]
这是功能还没做哈哈 https://github.com/ConnectAI-E/GitMaya/issues/106

**Comment by Leizhenpeng** [comment]
“默认优先展示已经关联chat的仓库” 就后端来做一下 @_user_1 @_user_2

**Comment by lloydzhou** [comment]
1. 前端已经处理了分页逻辑
2. 关于后端排序。还需要再考虑一下：
  a. 前两天讨论过多个repo关联一个群的需求，如果以后要兼容这个，需要将现在的数据结构改成repo.chat_group_id == chat_group.id
  b. 这样排序操作和当前数据结构的排序逻辑不太一样。
