### ISSUE TITLE
🐞 Bug 不支持新建带des的issue

### ISSUE THREAD

**Issue by Leizhenpeng** [ConnectAI-E/GitMaya#115]
## Issue Description 🤔

应该支持如下格式的issue创建
```
/issue @刘睿 
//name
repo界面需要优化
//des
增加一下分页，现在ConnectAI全部150多个仓库放在一起，太长了
默认优先展示已经关联chat的仓库
```
<img width="545" alt="image" src="https://github.com/ConnectAI-E/GitMaya/assets/50035229/2d74cdad-15d4-4a3c-81eb-87fada425cf8">

**Comment by freeziyou** [comment]
WIP

**Comment by freeziyou** [comment]
![image](https://github.com/ConnectAI-E/GitMaya/assets/33377207/7a3df7b3-2250-427f-9327-564791a71612)
使用飞书的展开全屏输入

**Comment by lloydzhou** [comment]
#133
