### ISSUE TITLE
🐞 Bug 通过回复的方式创建的issue显示异常，过滤一下不支持的消息格式，比如@用户

### ISSUE THREAD

**Issue by Leizhenpeng** [ConnectAI-E/GitMaya#118]

**Comment by Leizhenpeng** [comment]
<img width="823" alt="image" src="https://github.com/ConnectAI-E/GitMaya/assets/50035229/39f4e2ff-a762-46b6-80fb-4c0e24798c3d">

**Comment by freeziyou** [comment]
WIP
