### ISSUE TITLE
🐞 Bug chat模式下的帮助卡片下拉列表的仓库名单和网页版的Repo对不上

### ISSUE THREAD

**Issue by Leizhenpeng** [ConnectAI-E/GitMaya#124]

**Comment by Leizhenpeng** [comment]
![image](https://github.com/ConnectAI-E/GitMaya/assets/50035229/186c2104-c079-4782-ae01-270a3377273d)
<img width="1357" alt="image" src="https://github.com/ConnectAI-E/GitMaya/assets/50035229/77328f29-fc10-4d95-88fb-4aa012ce7d6e">

在网页中是有feishu-openai的，但是飞书消息卡片中没有

**Comment by lloydzhou** [comment]
https://open.feishu.cn/document/common-capabilities/message-card/add-card-interaction/interactive-components/selectmenu

这个selectMenu.options应该是有长度限制的，文档没有找到，需要找飞书官方确认
