### ISSUE TITLE
🐞 Bug issue 卡片更新时可能出现 repo 为 None 情况

### ISSUE THREAD

**Issue by freeziyou** [ConnectAI-E/GitMaya#128]
## Issue Description 🤔

issue 卡片更新时可能出现 repo 为 None 情况

## Additional Information 📝

/server/tasks/github/issue.py
![image](https://github.com/ConnectAI-E/GitMaya/assets/33377207/b87479a3-fed7-45b6-a149-d3248d782ef6)

**Comment by freeziyou** [comment]
可能是使用者配错github回调地址到gitmaya了，要检测application id是否和gitmaya相同

**Comment by freeziyou** [comment]
![image](https://github.com/ConnectAI-E/GitMaya/assets/33377207/b5859757-8f3a-4666-a9d7-f4b1d0dfbe7f)
40d27b49-790f-4c04-aa8d-f2bcd65157c4

**Comment by lloydzhou** [comment]
已修复 https://github.com/ConnectAI-E/GitMaya/pull/200
