### ISSUE TITLE
repo卡片信息和Github那边不一致

### ISSUE THREAD

**Issue by Leizhenpeng** [ConnectAI-E/GitMaya#131]

**Comment by Leizhenpeng** [comment]
![](img_v3_027c_2bce31c7-a3b0-4209-b49c-e3280bbad61g)

**Comment by Leizhenpeng** [comment]
![](img_v3_027c_c981f7e8-322f-4569-b3d2-8d0cdc73f40g)

**Comment by Leizhenpeng** [comment]
star的数目

**Comment by lloydzhou** [comment]
star的事件应该没有处理

**Comment by lloydzhou** [comment]
也就是说start的时候会发repo update事件

**Comment by jingfelix** [comment]
不是，是都会带 repository 这个信息

**Comment by lloydzhou** [comment]
反正监听一下star事件，触发　tasks.update_repo_info(repo_id)就好了

**Comment by freeziyou** [comment]
WIP

**Comment by freeziyou** [comment]
#139
