### ISSUE TITLE
官网加上gitmaya的介绍视频

### ISSUE THREAD

**Issue by Leizhenpeng** [ConnectAI-E/GitMaya#137]
考虑我们第一阶段只有飞书，潜在用户肯定是国内的，就弹出一个浮层，播放的是Bilibili视频 iframe  
[https://www.bilibili.com/video/BV1se411n7tD/](https://www.bilibili.com/video/BV1se411n7tD/)

**Comment by Dogtiti** [comment]
直接新页面跳转到b站

**Comment by Leizhenpeng** [comment]
@Dogtiti 这个部署上了吗

**Comment by Leizhenpeng** [comment]
@Leizhenpeng
