### ISSUE TITLE
🐞 Bug Repo 卡片的 homepage url 在为空的时候显示异常

### ISSUE THREAD

**Issue by Leizhenpeng** [ConnectAI-E/GitMaya#141]

**Comment by Leizhenpeng** [comment]
<img width="784" alt="image" src="https://github.com/ConnectAI-E/GitMaya/assets/50035229/cb3dc65a-b2eb-4a00-9ad9-14cc77e0fe8d">

**Comment by freeziyou** [comment]
WIP
