### ISSUE TITLE
🐞 Bug pr 下的 git msg的阶段太短了，

### ISSUE THREAD

**Issue by Leizhenpeng** [ConnectAI-E/GitMaya#146]
现在是多少阶段？看起来很奇怪

**Comment by Leizhenpeng** [comment]
![image](https://github.com/ConnectAI-E/GitMaya/assets/50035229/df33e3ec-81b9-4a51-813a-59b50d0d5c0a)

**Comment by lloydzhou** [comment]
截断

**Comment by Leizhenpeng** [comment]
typo 截断~

**Comment by freeziyou** [comment]
目前是每个分支名的前20个字符

**Comment by Leizhenpeng** [comment]
有些短了，测试一下飞书这边一行可以全部显示大概多少字符

**Comment by lloydzhou** [comment]
不能光看电脑端，这个卡片要考虑移动端查看
