### ISSUE TITLE
🐞 Bug issue下的 评论被编辑后，飞书那边没有更新

### ISSUE THREAD

**Issue by Leizhenpeng** [ConnectAI-E/GitMaya#147]

**Comment by Leizhenpeng** [comment]
可以看这个issue https://github.com/ConnectAI-E/GitMaya/issues/146

**Comment by freeziyou** [comment]
ok，一会加个编辑事件更新评论

**Comment by freeziyou** [comment]
这个还不太好加，我们没有存需要编辑的message_id。同理，编辑飞书消息后github也不太好更新@_user_1

**Comment by Leizhenpeng** [comment]
第一个问题可以在数据库加字段
第二个问题是什么原因，Github那边的消息是没有api来更新吗

**Comment by freeziyou** [comment]
有update_issue的api，但同样要comment_id

**Comment by Leizhenpeng** [comment]
都加上字段存一下

**Comment by freeziyou** [comment]
感觉得加表，github comment id和飞书消息message id是一对一绑定，comments和issue或pr是一对多，直接加在extra中很容易到长度上限

**Comment by Leizhenpeng** [comment]
看下~

**Comment by lloydzhou** [comment]
这是一个很弱的需求，我认为没必要加存储。实在要加编辑，就多发一条消息好了

**Comment by Leizhenpeng** [comment]
多发一条思路也可以  
- Github 编辑，飞书多发一条  
- 飞书编辑，Github多发一条

**Comment by freeziyou** [comment]
ok

**Comment by lloydzhou** [comment]
我感觉这个优先级不高，先处理优先级高的，影响使用的先做

**Comment by freeziyou** [comment]
飞书这边没有编辑消息事件，只能做从github编辑后，飞书多发一条

**Comment by freeziyou** [comment]
WIP, github编辑

**Comment by freeziyou** [comment]
#147 github编辑已完成，飞书编辑得等飞书支持

**Comment by Leizhenpeng** [comment]
飞书那边并没有打算支持，刚check，，，

**Comment by Leizhenpeng** [comment]
@freeziyou 对了，后面WIP也用label标识~ 方便看进度

**Comment by freeziyou** [comment]
ok

**Comment by freeziyou** [comment]
github编辑后重发新消息，飞书编辑得等飞书支持
