### ISSUE TITLE
@开头的评论，没有同步到Github

### ISSUE THREAD

**Issue by Leizhenpeng** [ConnectAI-E/GitMaya#161]

**Comment by Leizhenpeng** [comment]
<img width="937" alt="image" src="https://github.com/ConnectAI-E/GitMaya/assets/50035229/c59a2319-d1e4-407b-bfb0-b99c0525065a">

**Comment by Leizhenpeng** [comment]
https://github.com/ConnectAI-E/GitMaya/issues/160

**Comment by freeziyou** [comment]
#106 和这个一起处理 WIP

**Comment by freeziyou** [comment]
#164
