### ISSUE TITLE
点击logout按钮，没有任何反应，刷新后还是有登录状态

### ISSUE THREAD

**Issue by yaway** [ConnectAI-E/GitMaya#169]

**Comment by yaway** [comment]
![](img_v3_027k_8ac8a25c-d7a1-44e7-b95f-cde2557d463g)

**Comment by freeziyou** [comment]
![img_v3_027k_8ac8a25c-d7a1-44e7-b95f-cde2557d463g](https://github.com/ConnectAI-E/GitMaya/assets/33377207/c2e451d8-cc44-4ea6-8dbc-9e90ab48eb41)

**Comment by DDMeaqua** [comment]
@Dogtiti https://github.com/ConnectAI-E/GitMaya-Frontend/pull/34 提交pr了，有空review下
