### ISSUE TITLE
创建简单的issue的时候在遇到多行内容时候识别失败

### ISSUE THREAD

**Issue by Leizhenpeng** [ConnectAI-E/GitMaya#184]

**Comment by Leizhenpeng** [comment]
<img width="795" alt="image" src="https://github.com/ConnectAI-E/GitMaya/assets/50035229/8a01ac60-c7ab-437c-b793-99188d773d46">

**Comment by Leizhenpeng** [comment]
测试文案
```
/issue 不支持的邮箱在前端的input可以做一层校验
文案提醒我们支持的邮箱
不允许点击发送验证码
@刘睿  feature
```

**Comment by freeziyou** [comment]
展开发送issue有特定的格式，正文第一行固定：/issue +@负责人 + label，第二行开始才是描述

**Comment by Leizhenpeng** [comment]
没有展开就是单行文本里面换行，并没有点击左下角的展开符号

**Comment by Leizhenpeng** [comment]
测红一下，输入框里面的换行操作盒展开操作，在接受消息格式是不是有区别

**Comment by freeziyou** [comment]
要加空格，'''/issue 不支持的邮箱在前端的input可以做一层校验
文案提醒我们支持的邮箱
不允许点击发送验证码
@刘睿feature

**Comment by freeziyou** [comment]
测试了下，单行文本里面不支持换行，但是在单行文本换行就有点奇怪

**Comment by freeziyou** [comment]
多行展开发送比较合适

**Comment by lloydzhou** [comment]
这个不应该支持，命令就应该保持在一行。　　　　
而且issue标题也适合使用多行文本。
需要多行，应该放body里面。这个时候，应该使用post格式提交

**Comment by Leizhenpeng** [comment]
> 测试了下，单行文本里面不支持换行，但是在单行文本换行就有点奇怪

shift+enter

**Comment by freeziyou** [comment]
@Leizhenpeng 单行输入框只支持 /issue 标题 @负责人 labels，不支持添加描述
描述只能在展开输入框中输入，
```
标题
/issue @负责人 labels
描述
```
