### ISSUE TITLE
从github发出的issue comment，同步到飞书之后空格会消失

### ISSUE THREAD

**Issue by yaway** [ConnectAI-E/GitMaya#193]
![image](https://github.com/ConnectAI-E/GitMaya/assets/844157/c56c4553-3c7f-4142-8fde-f057ab944ec1)
![image](https://github.com/ConnectAI-E/GitMaya/assets/844157/07c8723f-26d6-4b61-b9f8-5f887a999e3c)

**Comment by freeziyou** [comment]
#195
