### ISSUE TITLE
private仓库传图上传不了

### ISSUE THREAD

**Issue by freeziyou** [ConnectAI-E/GitMaya#194]

**Comment by lloydzhou** [comment]
https://docs.github.com/en/rest/markdown/markdown?apiVersion=2022-11-28#render-a-markdown-document

如果是私有仓库，试试用这个先渲染成html。

试试看这个渲染之后的html里面的链接是不是有权限？

**Comment by lloydzhou** [comment]
```
![image](https://github.com/ConnectAI-E/GitMaya/assets/1826685/24e5782e-2045-4fd3-80b1-b261ebc497b9)
```
直接在页面上查看的时候，渲染出来的是带jwt的链接，域名也是`https://private-user-images.githubusercontent.com/`
![image](https://github.com/ConnectAI-E/GitMaya/assets/1826685/2bb0e843-f59f-480f-96dc-12f1fc781d30)

**Comment by freeziyou** [comment]
![image](https://github.com/ConnectAI-E/GitMaya/assets/33377207/97164a98-04bf-42a7-82d8-fd75f13cd2c7)
![image](https://github.com/ConnectAI-E/GitMaya/assets/33377207/453f05a6-dad1-4287-9286-a287ed372617)
markdown的api并不会做解析，github应该是在markdown渲染器有额外的未公开的上传接口

**Comment by lloydzhou** [comment]
https://docs.github.com/en/rest/releases/assets?apiVersion=2022-11-28#upload-a-release-asset
往github上传图片，或许可以走这个逻辑。
创建一个draft  release
往这个release_id上传assets
从返回的 "browser_download_url": "https://github.com/octocat/Hello-World/releases/download/v1.0.0/example.zip", 拿到链接，拿这个链接往相同的repo的issue里面填，应该权限就是一样的了。能看，大家都能看。不能看，大家都不能看
下载的时候，把个人的token放到header里面就能下载了

**Comment by jingfelix** [comment]
> ```
> ![image](https://github.com/ConnectAI-E/GitMaya/assets/1826685/24e5782e-2045-4fd3-80b1-b261ebc497b9)
> ```
> 
> 直接在页面上查看的时候，渲染出来的是带jwt的链接，域名也是`https://private-user-images.githubusercontent.com/` ![image](https://private-user-images.githubusercontent.com/1826685/301797981-2bb0e843-f59f-480f-96dc-12f1fc781d30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NzUyNjUsIm5iZiI6MTcwNjg3NDk2NSwicGF0aCI6Ii8xODI2Njg1LzMwMTc5Nzk4MS0yYmIwZTg0My1mNTlmLTQ4MGYtOTZkYy0xMmYxZmM3ODFkMzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDJUMTE1NjA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzA0MjJlY2Y0NDM4Y2MzMDI2OGIwNmIyYWFhNjY5MTdiN2IzZjlkMDgwZGVkMzVmNzhiY2QyMjM4NTE1NGQ2NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.uymIooJ4BHcCmxmlw5yoVvu26hgRNrkTo-RizwIYiE4)

能不能用 GitHub App 的 JWT 试一下能否访问？

**Comment by freeziyou** [comment]
刚刚试了下直接带用户token请求https://github.com/ConnectAI-E/GitMaya/assets/1826685/24e5782e-2045-4fd3-80b1-b261ebc497b9可以下载到图片

**Comment by lloydzhou** [comment]
我前面的那个消息放错位置了。那个是希望能处理飞书那边的图片传github的问题。

现在github这边私有仓库的图片，可以直接使用用户的token下载，再上传到飞书

**Comment by freeziyou** [comment]
#237 直接显示图片链接，这种方案相当于github帮我们做了权限验证
