### ISSUE TITLE
根据回复内容创建issue时候，label 创建失败

### ISSUE THREAD

**Issue by Leizhenpeng** [ConnectAI-E/GitMaya#196]

**Comment by Leizhenpeng** [comment]
<img width="385" alt="image" src="https://github.com/ConnectAI-E/GitMaya/assets/50035229/ccfa89c8-1eea-4e60-9aaf-113750b19fab">

**Comment by freeziyou** [comment]
label不加#，直接输入，多个label用英文逗号分隔

**Comment by freeziyou** [comment]
![image](https://github.com/ConnectAI-E/GitMaya/assets/33377207/653302ec-02ef-4f30-b31b-4a541a608358)
@Leizhenpeng mac从github传图默认是html格式吗

**Comment by Leizhenpeng** [comment]
不一定，也有 md

**Comment by lloydzhou** [comment]
这里一直提的需求都是不带#　多个label逗号分隔。

所以这里不是bug，本身逻辑是正确的，这个issue先关闭

**Comment by Leizhenpeng** [comment]
我怎么脑袋里及得什么时候提过#的事情，@freeziyou

**Comment by Leizhenpeng** [comment]
是展开时候的操作吗
