### ISSUE TITLE
People 页面绑定飞书账号选择器支持搜索

### ISSUE THREAD

**Issue by yaway** [ConnectAI-E/GitMaya#201]
申请绑定的多了可能会找不过来  
![](img_v3_027m_764320fa-ffa2-4d6a-ad07-44616d99512g)

**Comment by yaway** [comment]
![](img_v3_027m_77065884-983f-4b9f-921c-fb48adf901bg)

**Comment by yaway** [comment]
图片好像还是没有上传成功

**Comment by freeziyou** [comment]
@yaway 从飞书传图到github还没写

**Comment by lloydzhou** [comment]
https://github.com/ConnectAI-E/GitMaya/issues/174

**Comment by lloydzhou** [comment]
https://github.com/ConnectAI-E/GitMaya-Frontend/pull/35
