### ISSUE TITLE
修改网页中文文案

### ISSUE THREAD

**Issue by Leizhenpeng** [ConnectAI-E/GitMaya#205]

**Comment by Leizhenpeng** [comment]
修改意见
使Git就在聊天中流畅 -> 聊天即协同

尝试使用你的Github -> 立刻为GitHub组织安装
英文版也要改
Try with your github ->Try with your github org

**Comment by Leizhenpeng** [comment]
![](img_v3_027o_f0075b62-0d18-408c-9682-6fa7f166e70g)

**Comment by Leizhenpeng** [comment]
进行登录 - 授权登录

**Comment by Leizhenpeng** [comment]
<img width="1084" alt="image" src="https://github.com/ConnectAI-E/GitMaya/assets/50035229/132e79e3-1d0c-433b-bbcb-537802ac8195">

**Comment by Leizhenpeng** [comment]
遗漏，没有翻译  
![](img_v3_027o_45bee07e-0d8b-49de-97da-93c1e5284e5g)

**Comment by Leizhenpeng** [comment]
<img width="1355" alt="image" src="https://github.com/ConnectAI-E/GitMaya/assets/50035229/9b802f3d-c8dd-4d63-b398-249c85275e50">

**Comment by Leizhenpeng** [comment]
![](img_v3_027o_9a00bf61-0ec6-4cf9-9a75-1f9d9c3db6bg)

**Comment by DDMeaqua** [comment]
https://github.com/ConnectAI-E/GitMaya-Frontend/pull/36  提pr了@Leizhenpeng

**Comment by Leizhenpeng** [comment]
@Dogtiti 看能不能整个preview，方便预览前端的效果
