### ISSUE TITLE
在网页端增加「加入测试组织，免安装体验全部功能」的引导

### ISSUE THREAD

**Issue by Leizhenpeng** [ConnectAI-E/GitMaya#206]

**Comment by yaway** [comment]
@Dogtiti 在官网导航额外加一个引导链接到试用问卷吧，我想一个引导文案

**Comment by Dogtiti** [comment]
加什么样的？

**Comment by yaway** [comment]
我想想加个什么图标，跟现在飞书社区的并排放一个入口

**Comment by yaway** [comment]
![](img_v3_027o_bbf48e72-e2d9-41c1-9950-39810ed26bfg)

**Comment by yaway** [comment]
@Dogtiti 来个类似礼盒打开的图标？@Leizhenpeng 有啥想法没

**Comment by yaway** [comment]
https://fork-way.feishu.cn/share/base/form/shrcnVMJP4h2BKi9zlnWEh7DOJB?iframeFrom=docx&ccm_open=iframe 链接放这个就行

**Comment by Leizhenpeng** [comment]
111

**Comment by Leizhenpeng** [comment]
@

**Comment by Leizhenpeng** [comment]
看看新版的效果再提修改意见
