### ISSUE TITLE
Github desc 部分的图片没有传到飞书这边来

### ISSUE THREAD

**Issue by Leizhenpeng** [ConnectAI-E/GitMaya#217]
<img width="601" alt="image" src="https://github.com/ConnectAI-E/GitMaya/assets/50035229/23560656-3e7d-4608-bd77-cdd896a680d9">

不知道是不是私有仓库的原因

**Comment by freeziyou** [comment]
是私有仓库的原因，现在还在找解决方案 #194

**Comment by freeziyou** [comment]
问题重复
