### ISSUE TITLE
在Github发起代码块开头的issue ，飞书这边无法接受

### ISSUE THREAD

**Issue by Leizhenpeng** [ConnectAI-E/GitMaya#219]

**Comment by freeziyou** [comment]
![image](https://github.com/ConnectAI-E/GitMaya/assets/33377207/297d080e-7f5f-48f5-863f-0bb9747786a6)
飞书能够正常显示代码块，这是过长问题

**Comment by freeziyou** [comment]
过长问题已在 #228 处理
