### ISSUE TITLE
🐞 issue 描述中的@ 飞书么有处理

### ISSUE THREAD

**Issue by Leizhenpeng** [ConnectAI-E/GitMaya#221]
预期在 github description 中的@，飞书也消息卡片也要@对应人

**Comment by lloydzhou** [comment]
![image](https://github.com/ConnectAI-E/GitMaya/assets/1826685/8e439dec-bb15-4806-bab3-83e0adb9c2dc)
看这个issue，是有处理描述中的 at 人员的

**Comment by lloydzhou** [comment]
这里是从github创建的，我还以为是从飞书创建的issue

**Comment by Leizhenpeng** [comment]
对，就是因为有内部信息，我就不截图了。
