### ISSUE TITLE
飞书用户选单刷新后仍然无法显示新添加的用户

### ISSUE THREAD

**Issue by yaway** [ConnectAI-E/GitMaya#225]

**Comment by yaway** [comment]
![](img_v3_0288_34c930c8-f4f5-48f3-ac4d-fcfd11ec6deg)

**Comment by yaway** [comment]
![](img_v3_0288_08d21dd2-7d85-4176-b11f-dbc00744d8dg)

**Comment by freeziyou** [comment]
改名前有出现在选单，改名后新旧名字都没有出现，是这个意思吗

**Comment by yaway** [comment]
![](img_v3_0289_4ce78e88-31d7-4332-bb7e-a7fb5241f28g)  
![](img_v3_0289_6431df03-c08d-49cc-8b36-bf33f4c242ag)

**Comment by yaway** [comment]
这两个人已经加入到飞书了，但是名字没有显示在gitmaya绑定的选单里

**Comment by yaway** [comment]
改名=从手机号名称改为他们的github的名称

**Comment by yaway** [comment]
我的测试账号是 yaway.fe@gmail.com

**Comment by yaway** [comment]
测试团队叫GitMayaTest

**Comment by freeziyou** [comment]
尝试手动刷新看看

**Comment by freeziyou** [comment]
![](img_v3_0289_e2c91b82-4773-4af8-8609-237c56a2b49g)
