### ISSUE TITLE
绑定人员搜索

### ISSUE THREAD

**Issue by lloydzhou** [ConnectAI-E/GitMaya#226]
上次把绑定人员搜索这里改了，从下拉选项改成了支持搜索。  
但是现在只支持本地搜索，希望支持通过api搜索

**Comment by lloydzhou** [comment]
#225

**Comment by yaway** [comment]
@Dogtiti 求尽快修复[红脸] 试用邀请卡在这里了

**Comment by lloydzhou** [comment]
@Dogtiti 可以先简单的通过把size配置一个大一些的值，先临时处理一下

**Comment by Dogtiti** [comment]
我一会儿看看

**Comment by Dogtiti** [comment]
@yaway 好了 可以找人发布一下

**Comment by freeziyou** [comment]
@lloydzhou 林哥，前端需要重新发一版，website镜像才更新

**Comment by lloydzhou** [comment]
ok
