### ISSUE TITLE
🐞 Bug typo mistake 

### ISSUE THREAD

**Issue by Leizhenpeng** [ConnectAI-E/GitMaya#98]
## Issue Description 🤔

chat状态下的帮助文案错误
![](https://github.com/ConnectAI-E/GitMaya/assets/50035229/cc43e1e0-5839-4cb7-a03b-3bd0fcfcc149)
<img width="853" alt="image" src="">

**Comment by freeziyou** [comment]
已更正

**Comment by freeziyou** [comment]
#102 fix typo
